// <auto-generated />
using System;
using E_learning;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace WebBanSach.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20221216081615_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("WebBanSach.Models.Admin.Admin", b =>
                {
                    b.Property<string>("userAdmin")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("passAdmin")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("userAdmin");

                    b.ToTable("Admins");
                });

            modelBuilder.Entity("WebBanSach.Models.ChiTiet_DonDatHang", b =>
                {
                    b.Property<Guid>("MaDonHang")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("MaSach")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("DonGia")
                        .HasColumnType("float");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.HasKey("MaDonHang", "MaSach");

                    b.HasIndex("MaSach");

                    b.ToTable("ChiTiet_DonDatHang");
                });

            modelBuilder.Entity("WebBanSach.Models.ChuDe", b =>
                {
                    b.Property<Guid>("MaChuDe")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TenChuDe")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaChuDe");

                    b.ToTable("ChuDe");
                });

            modelBuilder.Entity("WebBanSach.Models.DonDatHang", b =>
                {
                    b.Property<Guid>("MaDonHang")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("MaKH")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("NgayDat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayGiao")
                        .HasColumnType("datetime2");

                    b.Property<byte>("TinhTrangGiaoHang")
                        .HasColumnType("tinyint");

                    b.Property<byte>("TinhTrangThanhToan")
                        .HasColumnType("tinyint");

                    b.HasKey("MaDonHang");

                    b.HasIndex("MaKH");

                    b.ToTable("DonDatHang");
                });

            modelBuilder.Entity("WebBanSach.Models.KhachHang", b =>
                {
                    b.Property<Guid>("MaKH")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("DienThoai")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("NgaySinh")
                        .HasColumnType("datetime2");

                    b.Property<string>("TaiKhoan")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("MaKH");

                    b.HasIndex("Email", "TaiKhoan")
                        .IsUnique();

                    b.ToTable("KhachHang");
                });

            modelBuilder.Entity("WebBanSach.Models.NhaXuatBan", b =>
                {
                    b.Property<Guid>("MaNXB")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("DienThoai")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("TenNXB")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaNXB");

                    b.ToTable("NhaXuatBan");
                });

            modelBuilder.Entity("WebBanSach.Models.Sach", b =>
                {
                    b.Property<Guid>("MaSach")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AnhBia")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<double>("GiaBan")
                        .HasColumnType("float");

                    b.Property<Guid>("MaChuDe")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("MaNXB")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MoTa")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<int>("SoLuongTon")
                        .HasColumnType("int");

                    b.Property<string>("TenSach")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MaSach");

                    b.HasIndex("MaChuDe");

                    b.HasIndex("MaNXB");

                    b.ToTable("Sach");
                });

            modelBuilder.Entity("WebBanSach.Models.TacGia", b =>
                {
                    b.Property<Guid>("MaTacGia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("DienThoai")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("TenTacGia")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TieuSu")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("MaTacGia");

                    b.ToTable("TacGia");
                });

            modelBuilder.Entity("WebBanSach.Models.VietSach", b =>
                {
                    b.Property<Guid>("MaTacGia")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("MaSach")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("VaiTro")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ViTri")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaTacGia", "MaSach");

                    b.HasIndex("MaSach");

                    b.ToTable("VietSach");
                });

            modelBuilder.Entity("WebBanSach.Models.ChiTiet_DonDatHang", b =>
                {
                    b.HasOne("WebBanSach.Models.DonDatHang", "DonDatHang")
                        .WithMany("listChiTiet_DDH")
                        .HasForeignKey("MaDonHang")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebBanSach.Models.Sach", "Sach")
                        .WithMany("listChiTiet_DDH")
                        .HasForeignKey("MaSach")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DonDatHang");

                    b.Navigation("Sach");
                });

            modelBuilder.Entity("WebBanSach.Models.DonDatHang", b =>
                {
                    b.HasOne("WebBanSach.Models.KhachHang", "KhachHang")
                        .WithMany("listDonDatHang")
                        .HasForeignKey("MaKH")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KhachHang");
                });

            modelBuilder.Entity("WebBanSach.Models.Sach", b =>
                {
                    b.HasOne("WebBanSach.Models.ChuDe", "ChuDe")
                        .WithMany("listSach")
                        .HasForeignKey("MaChuDe")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebBanSach.Models.NhaXuatBan", "NhaXuatBan")
                        .WithMany("listSach")
                        .HasForeignKey("MaNXB")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChuDe");

                    b.Navigation("NhaXuatBan");
                });

            modelBuilder.Entity("WebBanSach.Models.VietSach", b =>
                {
                    b.HasOne("WebBanSach.Models.Sach", "Sach")
                        .WithMany("listVietSach")
                        .HasForeignKey("MaSach")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebBanSach.Models.TacGia", "TacGia")
                        .WithMany("listVietSach")
                        .HasForeignKey("MaTacGia")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sach");

                    b.Navigation("TacGia");
                });

            modelBuilder.Entity("WebBanSach.Models.ChuDe", b =>
                {
                    b.Navigation("listSach");
                });

            modelBuilder.Entity("WebBanSach.Models.DonDatHang", b =>
                {
                    b.Navigation("listChiTiet_DDH");
                });

            modelBuilder.Entity("WebBanSach.Models.KhachHang", b =>
                {
                    b.Navigation("listDonDatHang");
                });

            modelBuilder.Entity("WebBanSach.Models.NhaXuatBan", b =>
                {
                    b.Navigation("listSach");
                });

            modelBuilder.Entity("WebBanSach.Models.Sach", b =>
                {
                    b.Navigation("listChiTiet_DDH");

                    b.Navigation("listVietSach");
                });

            modelBuilder.Entity("WebBanSach.Models.TacGia", b =>
                {
                    b.Navigation("listVietSach");
                });
#pragma warning restore 612, 618
        }
    }
}
